<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
      * Auto generated seed file

      @return void
     */
    public function run()
    {


        \DB::table('permissions')->delete();

        \DB::table('permissions')->insert(array(
            0 =>
                array(
                    'id' => 1,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'مجموعات المستخدمين',
                    'name' => 'admin.roles.index',
                    'description' => NULL,
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 0,
                    'sort' => 1,
                    'show_in_menu' => 1,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            1 =>
                array(
                    'id' => 2,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'roles',
                    'controller' => 'App\\Http\\Controllers\\Admin\\RolesController::class',
                    'action' => 'getIndex',
                    'title' => 'المجموعات',
                    'name' => 'admin.roles.view',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 1,
                    'sort' => 1,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            2 =>
                array(
                    'id' => 3,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'roles/list',
                    'controller' => 'App\\Http\\Controllers\\Admin\\RolesController::class',
                    'action' => 'getList',
                    'title' => 'عرض المجموعات',
                    'name' => 'admin.roles.list',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 1,
                    'sort' => 2,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            3 =>
                array(
                    'id' => 4,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'roles/add',
                    'controller' => 'App\\Http\\Controllers\\Admin\\RolesController::class',
                    'action' => 'getAdd',
                    'title' => 'إضافة مجموعة',
                    'name' => 'admin.roles.add',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 1,
                    'sort' => 3,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            4 =>
                array(
                    'id' => 5,
                    'group_id' => 1,
                    'request_type' => 'post',
                    'url' => 'roles/add',
                    'controller' => 'App\\Http\\Controllers\\Admin\\RolesController::class',
                    'action' => 'postAdd',
                    'title' => 'إضافة مجموعة',
                    'name' => 'admin.roles.post.add',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 1,
                    'sort' => 3,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            5 =>
                array(
                    'id' => 6,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'roles/edit/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\RolesController::class',
                    'action' => 'getEdit',
                    'title' => 'تعديل مجموعة',
                    'name' => 'admin.roles.edit',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 1,
                    'sort' => 4,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            6 =>
                array(
                    'id' => 7,
                    'group_id' => 1,
                    'request_type' => 'post',
                    'url' => 'roles/edit/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\RolesController::class',
                    'action' => 'postEdit',
                    'title' => 'تعديل مجموعة',
                    'name' => 'admin.roles.post.edit',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 1,
                    'sort' => 3,
                    'show_in_menu' => 0,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            7 =>
                array(
                    'id' => 8,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'roles/delete/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\RolesController::class',
                    'action' => 'getDelete',
                    'title' => 'حذف مجموعة',
                    'name' => 'admin.roles.delete',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 1,
                    'sort' => 5,
                    'show_in_menu' => 0,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            8 =>
                array(
                    'id' => 9,
                    'group_id' => 1,
                    'request_type' => 'post',
                    'url' => 'roles/status',
                    'controller' => 'App\\Http\\Controllers\\Admin\\RolesController::class',
                    'action' => 'postStatus',
                    'title' => 'تعديل حالة مجموعة',
                    'name' => 'admin.roles.status',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 1,
                    'sort' => 3,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            9 =>
                array(
                    'id' => 10,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'roles/permissions/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\RolesController::class',
                    'action' => 'getPermissions',
                    'title' => 'تعديل صلاحيات المجموعات',
                    'name' => 'admin.roles.permissions',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 1,
                    'sort' => 3,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            10 =>
                array(
                    'id' => 11,
                    'group_id' => 1,
                    'request_type' => 'post',
                    'url' => 'roles/permissions/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\RolesController::class',
                    'action' => 'postPermissions',
                    'title' => 'تعديل صلاحيات المجموعات',
                    'name' => 'admin.roles.post.permissions',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 1,
                    'sort' => 3,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            11 =>
                array(
                    'id' => 12,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'المستخدمون',
                    'name' => 'admin.users.view',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 0,
                    'sort' => 2,
                    'show_in_menu' => 1,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            12 =>
                array(
                    'id' => 13,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'users',
                    'controller' => 'App\\Http\\Controllers\\Admin\\UsersController::class',
                    'action' => 'getIndex',
                    'title' => 'المستخدمون',
                    'name' => 'admin.users.view',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 12,
                    'sort' => 1,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            13 =>
                array(
                    'id' => 14,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'users/list',
                    'controller' => 'App\\Http\\Controllers\\Admin\\UsersController::class',
                    'action' => 'getList',
                    'title' => 'عرض المستخدمين',
                    'name' => 'admin.users.list',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 12,
                    'sort' => 2,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            14 =>
                array(
                    'id' => 15,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'users/add',
                    'controller' => 'App\\Http\\Controllers\\Admin\\UsersController::class',
                    'action' => 'getAdd',
                    'title' => 'إضافة مستخدم',
                    'name' => 'admin.users.add',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 12,
                    'sort' => 3,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            15 =>
                array(
                    'id' => 16,
                    'group_id' => 1,
                    'request_type' => 'post',
                    'url' => 'users/add',
                    'controller' => 'App\\Http\\Controllers\\Admin\\UsersController::class',
                    'action' => 'postAdd',
                    'title' => 'إضافة مستخدم',
                    'name' => 'admin.users.store',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 12,
                    'sort' => 3,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            16 =>
                array(
                    'id' => 17,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'users/edit/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\UsersController::class',
                    'action' => 'getEdit',
                    'title' => 'تعديل مستخدم',
                    'name' => 'admin.users.edit',
                    'description' => NULL,
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 12,
                    'sort' => 1,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            17 =>
                array(
                    'id' => 18,
                    'group_id' => 1,
                    'request_type' => 'post',
                    'url' => 'users/edit/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\UsersController::class',
                    'action' => 'postEdit',
                    'title' => 'تعديل مستخدم',
                    'name' => 'admin.users.update',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 1,
                    'sort' => 3,
                    'show_in_menu' => 0,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),

            18 =>
                array(
                    'id' => 19,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'users/delete/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\UsersController::class',
                    'action' => 'getDelete',
                    'title' => 'حذف مستخدم',
                    'name' => 'admin.users.delete',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 1,
                    'sort' => 3,
                    'show_in_menu' => 0,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            19 =>
                array(
                    'id' => 20,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'التصنيفات',
                    'name' => 'admin.categories.view',
                    'description' => NULL,
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 0,
                    'sort' => 1,
                    'show_in_menu' => 1,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            20 =>
                array(
                    'id' => 21,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'categories',
                    'controller' => 'App\\Http\\Controllers\\Admin\\CategoriesController::class',
                    'action' => 'getIndex',
                    'title' => 'التصنيفات',
                    'name' => 'admin.categories.view',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 20,
                    'sort' => 1,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            21 =>
                array(
                    'id' => 22,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'categories/list',
                    'controller' => 'App\\Http\\Controllers\\Admin\\CategoriesController::class',
                    'action' => 'getList',
                    'title' => 'عرض التصنيفات',
                    'name' => 'admin.categories.list',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 20,
                    'sort' => 2,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            22 =>
                array(
                    'id' => 23,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'categories/add',
                    'controller' => 'App\\Http\\Controllers\\Admin\\CategoriesController::class',
                    'action' => 'getAdd',
                    'title' => 'إضافة تصنيف',
                    'name' => 'admin.categories.add',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 20,
                    'sort' => 3,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            23 =>
                array(
                    'id' => 24,
                    'group_id' => 1,
                    'request_type' => 'post',
                    'url' => 'categories/add',
                    'controller' => 'App\\Http\\Controllers\\Admin\\CategoriesController::class',
                    'action' => 'postAdd',
                    'title' => 'إضافة تصنيف',
                    'name' => 'admin.categories.post.add',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 20,
                    'sort' => 3,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            24 =>
                array(
                    'id' => 25,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'categories/edit/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\CategoriesController::class',
                    'action' => 'getEdit',
                    'title' => 'تعديل تصنيف',
                    'name' => 'admin.categories.edit',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 20,
                    'sort' => 4,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            25 =>
                array(
                    'id' => 26,
                    'group_id' => 1,
                    'request_type' => 'post',
                    'url' => 'categories/edit/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\CategoriesController::class',
                    'action' => 'postEdit',
                    'title' => 'تعديل تصنيف',
                    'name' => 'admin.categories.post.edit',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 20,
                    'sort' => 3,
                    'show_in_menu' => 0,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            26 =>
                array(
                    'id' => 27,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'categories/delete/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\CategoriesController::class',
                    'action' => 'getDelete',
                    'title' => 'حذف تصنيف',
                    'name' => 'admin.categories.delete',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 20,
                    'sort' => 5,
                    'show_in_menu' => 0,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            27 =>
                array(
                    'id' => 28,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'الأصناف',
                    'name' => 'admin.items.index',
                    'description' => NULL,
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 0,
                    'sort' => 1,
                    'show_in_menu' => 0,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            28 =>
                array (
                    'id' => 29,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'items',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ItemsController::class',
                    'action' => 'getIndex',
                    'title' => 'الأصناف',
                    'name' => 'admin.items.view',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 28,
                    'sort' => 1,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            29 =>
                array (
                    'id' => 30,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'items/list',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ItemsController::class',
                    'action' => 'getList',
                    'title' => 'عرض الأصناف',
                    'name' => 'admin.items.list',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 28,
                    'sort' => 2,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            30 =>
                array (
                    'id' => 31,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'items/add',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ItemsController::class',
                    'action' => 'getAdd',
                    'title' => 'إضافة صنف',
                    'name' => 'admin.items.add',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 28,
                    'sort' => 3,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            31 =>
                array (
                    'id' => 32,
                    'group_id' => 1,
                    'request_type' => 'post',
                    'url' => 'items/add',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ItemsController::class',
                    'action' => 'postAdd',
                    'title' => 'إضافة صنف',
                    'name' => 'admin.items.post.add',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 28,
                    'sort' => 3,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            32 =>
                array (
                    'id' => 33,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'items/edit/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ItemsController::class',
                    'action' => 'getEdit',
                    'title' => 'تعديل صنف',
                    'name' => 'admin.items.edit',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 28,
                    'sort' => 4,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            33 =>
                array (
                    'id' => 34,
                    'group_id' => 1,
                    'request_type' => 'post',
                    'url' => 'items/edit/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ItemsController::class',
                    'action' => 'postEdit',
                    'title' => 'تعديل صنف',
                    'name' => 'admin.items.post.edit',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 28,
                    'sort' => 3,
                    'show_in_menu' => 0,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            34 =>
                array (
                    'id' => 35,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'items/delete/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ItemsController::class',
                    'action' => 'getDelete',
                    'title' => 'حذف صنف',
                    'name' => 'admin.items.delete',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 28,
                    'sort' => 5,
                    'show_in_menu' => 0,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
//            35 =>
//                array(
//                    'id' => 36,
//                    'group_id' => 1,
//                    'request_type' => 'get',
//                    'url' => '',
//                    'controller' => '',
//                    'action' => '',
//                    'title' => 'إرساليات العهود',
//                    'name' => 'admin.batches.view',
//                    'description' => NULL,
//                    'guard_name' => 'admin',
//                    'icon' => 'icon-briefcase',
//                    'parent_id' => 0,
//                    'sort' => 1,
//                    'show_in_menu' => 1,
//                    'has_link' => 0,
//                    'created_at' => NULL,
//                    'updated_at' => NULL,
//                ),
//            36 =>
//                array(
//                    'id' => 37,
//                    'group_id' => 1,
//                    'request_type' => 'get',
//                    'url' => 'batches',
//                    'controller' => 'App\\Http\\Controllers\\Admin\\BatchesController::class',
//                    'action' => 'getIndex',
//                    'title' => 'إرساليات العهود',
//                    'name' => 'admin.batches.view',
//                    'description' => '',
//                    'guard_name' => 'admin',
//                    'icon' => 'icon-briefcase',
//                    'parent_id' => 36,
//                    'sort' => 1,
//                    'show_in_menu' => 1,
//                    'has_link' => 1,
//                    'created_at' => NULL,
//                    'updated_at' => NULL,
//                ),
//            37 =>
//                array(
//                    'id' => 38,
//                    'group_id' => 1,
//                    'request_type' => 'get',
//                    'url' => 'batches/list',
//                    'controller' => 'App\\Http\\Controllers\\Admin\\BatchesController::class',
//                    'action' => 'getList',
//                    'title' => 'عرض إرساليات العهود',
//                    'name' => 'admin.batches.list',
//                    'description' => '',
//                    'guard_name' => 'admin',
//                    'icon' => 'icon-briefcase',
//                    'parent_id' => 36,
//                    'sort' => 2,
//                    'show_in_menu' => 0,
//                    'has_link' => 1,
//                    'created_at' => NULL,
//                    'updated_at' => NULL,
//                ),
//            38 =>
//                array(
//                    'id' => 39,
//                    'group_id' => 1,
//                    'request_type' => 'get',
//                    'url' => 'batches/add',
//                    'controller' => 'App\\Http\\Controllers\\Admin\\BatchesController::class',
//                    'action' => 'getAdd',
//                    'title' => 'إضافة إرسالية العهود',
//                    'name' => 'admin.batches.add',
//                    'description' => '',
//                    'guard_name' => 'admin',
//                    'icon' => 'icon-briefcase',
//                    'parent_id' => 36,
//                    'sort' => 3,
//                    'show_in_menu' => 1,
//                    'has_link' => 1,
//                    'created_at' => NULL,
//                    'updated_at' => NULL,
//                ),
//            39 =>
//                array(
//                    'id' => 40,
//                    'group_id' => 1,
//                    'request_type' => 'post',
//                    'url' => 'batches/add',
//                    'controller' => 'App\\Http\\Controllers\\Admin\\BatchesController::class',
//                    'action' => 'postAdd',
//                    'title' => 'إضافة إرسالية العهود',
//                    'name' => 'admin.batches.post.add',
//                    'description' => '',
//                    'guard_name' => 'admin',
//                    'icon' => 'icon-briefcase',
//                    'parent_id' => 36,
//                    'sort' => 3,
//                    'show_in_menu' => 0,
//                    'has_link' => 1,
//                    'created_at' => NULL,
//                    'updated_at' => NULL,
//                ),
//            40 =>
//                array(
//                    'id' => 41,
//                    'group_id' => 1,
//                    'request_type' => 'get',
//                    'url' => 'batches/edit/{id}',
//                    'controller' => 'App\\Http\\Controllers\\Admin\\BatchesController::class',
//                    'action' => 'getEdit',
//                    'title' => 'تعديل إرسالية العهود',
//                    'name' => 'admin.batches.edit',
//                    'description' => '',
//                    'guard_name' => 'admin',
//                    'icon' => 'icon-briefcase',
//                    'parent_id' => 36,
//                    'sort' => 4,
//                    'show_in_menu' => 0,
//                    'has_link' => 1,
//                    'created_at' => NULL,
//                    'updated_at' => NULL,
//                ),
//            41 =>
//                array(
//                    'id' => 42,
//                    'group_id' => 1,
//                    'request_type' => 'post',
//                    'url' => 'batches/edit/{id}',
//                    'controller' => 'App\\Http\\Controllers\\Admin\\BatchesController::class',
//                    'action' => 'postEdit',
//                    'title' => 'تعديل إرسالية العهود',
//                    'name' => 'admin.batches.post.edit',
//                    'description' => '',
//                    'guard_name' => 'admin',
//                    'icon' => 'icon-briefcase',
//                    'parent_id' => 36,
//                    'sort' => 3,
//                    'show_in_menu' => 0,
//                    'has_link' => 0,
//                    'created_at' => NULL,
//                    'updated_at' => NULL,
//                ),
//            42 =>
//                array(
//                    'id' => 43,
//                    'group_id' => 1,
//                    'request_type' => 'get',
//                    'url' => 'batches/delete/{id}',
//                    'controller' => 'App\\Http\\Controllers\\Admin\\BatchesController::class',
//                    'action' => 'getDelete',
//                    'title' => 'حذف إرسالية العهود',
//                    'name' => 'admin.batches.delete',
//                    'description' => '',
//                    'guard_name' => 'admin',
//                    'icon' => 'icon-briefcase',
//                    'parent_id' => 36,
//                    'sort' => 5,
//                    'show_in_menu' => 0,
//                    'has_link' => 0,
//                    'created_at' => NULL,
//                    'updated_at' => NULL,
//                ),
            43 =>
                array(
                    'id' => 44,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'الأصناف',
                    'name' => 'admin.items.index',
                    'description' => NULL,
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 0,
                    'sort' => 1,
                    'show_in_menu' => 1,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            44 =>
                array (
                    'id' => 45,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'items',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ItemsController::class',
                    'action' => 'getIndex',
                    'title' => 'الأصناف',
                    'name' => 'admin.items.view',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 44,
                    'sort' => 1,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            45 =>
                array (
                    'id' => 46,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'items/list',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ItemsController::class',
                    'action' => 'getList',
                    'title' => 'عرض الأصناف',
                    'name' => 'admin.items.list',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 44,
                    'sort' => 2,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            46 =>
                array (
                    'id' => 47,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'items/add',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ItemsController::class',
                    'action' => 'getAdd',
                    'title' => 'إضافة صنف',
                    'name' => 'admin.items.add',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 44,
                    'sort' => 3,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            47 =>
                array (
                    'id' => 48,
                    'group_id' => 1,
                    'request_type' => 'post',
                    'url' => 'items/add',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ItemsController::class',
                    'action' => 'postAdd',
                    'title' => 'إضافة صنف',
                    'name' => 'admin.items.post.add',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 44,
                    'sort' => 3,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            48 =>
                array (
                    'id' => 49,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'items/add-items',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ItemsController::class',
                    'action' => 'getAddItems',
                    'title' => 'إضافة إرسالية',
                    'name' => 'admin.items.addItems',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 44,
                    'sort' => 3,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            49 =>
                array (
                    'id' => 50,
                    'group_id' => 1,
                    'request_type' => 'post',
                    'url' => 'items/add-items',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ItemsController::class',
                    'action' => 'postAddItems',
                    'title' => 'إضافة إرسالية',
                    'name' => 'admin.items.post.addItems',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 44,
                    'sort' => 3,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            50 =>
                array (
                    'id' => 51,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'items/edit/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ItemsController::class',
                    'action' => 'getEdit',
                    'title' => 'تعديل صنف',
                    'name' => 'admin.items.edit',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 44,
                    'sort' => 4,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            51 =>
                array (
                    'id' => 52,
                    'group_id' => 1,
                    'request_type' => 'post',
                    'url' => 'items/edit/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ItemsController::class',
                    'action' => 'postEdit',
                    'title' => 'تعديل صنف',
                    'name' => 'admin.items.post.edit',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 44,
                    'sort' => 3,
                    'show_in_menu' => 0,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            52 =>
                array (
                    'id' => 53,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'items/delete/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ItemsController::class',
                    'action' => 'getDelete',
                    'title' => 'حذف صنف',
                    'name' => 'admin.items.delete',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 44,
                    'sort' => 5,
                    'show_in_menu' => 0,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            53 =>
                array(
                    'id' => 54,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'العُهد',
                    'name' => 'admin.testaments.index',
                    'description' => NULL,
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 0,
                    'sort' => 1,
                    'show_in_menu' => 1,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            54 =>
                array (
                    'id' => 55,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'testaments',
                    'controller' => 'App\\Http\\Controllers\\Admin\\TestamentsController::class',
                    'action' => 'getIndex',
                    'title' => 'العُهد',
                    'name' => 'admin.testaments.view',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 54,
                    'sort' => 1,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            55 =>
                array (
                    'id' => 56,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'testaments/list',
                    'controller' => 'App\\Http\\Controllers\\Admin\\TestamentsController::class',
                    'action' => 'getList',
                    'title' => 'عرض العُهد',
                    'name' => 'admin.testaments.list',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 54,
                    'sort' => 2,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            56 =>
                array (
                    'id' => 57,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'testaments/add',
                    'controller' => 'App\\Http\\Controllers\\Admin\\TestamentsController::class',
                    'action' => 'getAdd',
                    'title' => "تحويل عُهدة من مخزن لشخص",
                    'name' => 'admin.testaments.add',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 54,
                    'sort' => 3,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            57 =>
                array (
                    'id' => 58,
                    'group_id' => 1,
                    'request_type' => 'post',
                    'url' => 'testaments/add',
                    'controller' => 'App\\Http\\Controllers\\Admin\\TestamentsController::class',
                    'action' => 'postAdd',
                    'title' =>"تحويل عُهدة من مخزن لشخص",
                    'name' => 'admin.testaments.post.add',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 54,
                    'sort' => 3,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            58 =>
                array (
                    'id' => 59,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'testaments/edit/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\TestamentsController::class',
                    'action' => 'getEdit',
                    'title' => 'تعديل عُهدة',
                    'name' => 'admin.testaments.edit',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 54,
                    'sort' => 4,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            59 =>
                array (
                    'id' => 60,
                    'group_id' => 1,
                    'request_type' => 'post',
                    'url' => 'testaments/edit/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\TestamentsController::class',
                    'action' => 'postEdit',
                    'title' => 'تعديل عُهدة',
                    'name' => 'admin.testaments.post.edit',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 54,
                    'sort' => 3,
                    'show_in_menu' => 0,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            60 =>
                array (
                    'id' => 61,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'testaments/delete/{id}',
                    'controller' => 'App\\Http\\Controllers\\Admin\\TestamentsController::class',
                    'action' => 'getDelete',
                    'title' => 'حذف عُهدة',
                    'name' => 'admin.testaments.delete',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 54,
                    'sort' => 5,
                    'show_in_menu' => 0,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            61 =>
                array (
                    'id' => 62,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'testaments/convert/person-to-person',
                    'controller' => 'App\\Http\\Controllers\\Admin\\TestamentsController::class',
                    'action' => 'getPersonToPerson',
                    'title' => 'تحويل عُهدة من شخص لشخص',
                    'name' => 'admin.testaments.convert.person_to_person',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 54,
                    'sort' => 6,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            62 =>
                array (
                    'id' => 63,
                    'group_id' => 1,
                    'request_type' => 'post',
                    'url' => 'testaments/convert/person-to-person',
                    'controller' => 'App\\Http\\Controllers\\Admin\\TestamentsController::class',
                    'action' => 'postPersonToPerson',
                    'title' => 'تحويل عُهدة من شخص لشخص',
                    'name' => 'admin.testaments.post.convert.person_to_person',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 54,
                    'sort' => 6,
                    'show_in_menu' => 0,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            63 =>
                array (
                    'id' => 64,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'testaments/convert/person-to-store',
                    'controller' => 'App\\Http\\Controllers\\Admin\\TestamentsController::class',
                    'action' => 'getPersonToStore',
                    'title' => 'تحويل عُهدة من شخص لمخزن',
                    'name' => 'admin.testaments.convert.person_to_store',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 54,
                    'sort' => 7,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            64 =>
                array (
                    'id' => 65,
                    'group_id' => 1,
                    'request_type' => 'post',
                    'url' => 'testaments/convert/person-to-store',
                    'controller' => 'App\\Http\\Controllers\\Admin\\TestamentsController::class',
                    'action' => 'postPersonToStore',
                    'title' => 'تحويل عُهدة من شخص لمخزن',
                    'name' => 'admin.testaments.post.convert.person_to_store',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 54,
                    'sort' => 7,
                    'show_in_menu' => 0,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            65 =>
                array (
                    'id' => 66,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'testaments/convert/store-to-store',
                    'controller' => 'App\\Http\\Controllers\\Admin\\TestamentsController::class',
                    'action' => 'getStoreToStore',
                    'title' => 'تحويل عُهدة من مخرن لمخزن',
                    'name' => 'admin.testaments.convert.store_to_store',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 54,
                    'sort' => 8,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            66 =>
                array (
                    'id' => 67,
                    'group_id' => 1,
                    'request_type' => 'post',
                    'url' => 'testaments/convert/store-to-store',
                    'controller' => 'App\\Http\\Controllers\\Admin\\TestamentsController::class',
                    'action' => 'postStoreToStore',
                    'title' => 'تحويل عُهدة من مخرن لمخزن',
                    'name' => 'admin.testaments.post.convert.store_to_store',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 54,
                    'sort' => 8,
                    'show_in_menu' => 0,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            67 =>
                array(
                    'id' => 68,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'السجلات',
                    'name' => 'admin.transactions.index',
                    'description' => NULL,
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 0,
                    'sort' => 1,
                    'show_in_menu' => 1,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            68 =>
                array (
                    'id' => 69,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'transactions',
                    'controller' => 'App\\Http\\Controllers\\Admin\\TransactionsController::class',
                    'action' => 'getIndex',
                    'title' => "سجلات العُهد",
                    'name' => 'admin.transactions.view',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 68,
                    'sort' => 1,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            69 =>
                array (
                    'id' => 70,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'transactions/list',
                    'controller' => 'App\\Http\\Controllers\\Admin\\TransactionsController::class',
                    'action' => 'getList',
                    'title' => "سجل الحركات",
                    'name' => 'admin.transactions.list',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 68,
                    'sort' => 2,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            70 =>
                array(
                    'id' => 71,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'التقارير',
                    'name' => 'admin.reports.index',
                    'description' => NULL,
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 0,
                    'sort' => 1,
                    'show_in_menu' => 1,
                    'has_link' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            71 =>
                array (
                    'id' => 72,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'store-employee-testaments-report',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ReportsController::class',
                    'action' => 'store_employee_testaments_report',
                    'title' => 'كشف عهدة الموظف أو المخزن',
                    'name' => 'admin.reports.store_employee_testaments_report',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 71,
                    'sort' => 1,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            72 =>
                array (
                    'id' => 73,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'store-employee-testaments-report/export-pdf',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ReportsController::class',
                    'action' => 'export_store_employee_testaments_report',
                    'title' => 'تصدير التقرير',
                    'name' => 'admin.reports.export_store_employee_testaments_report',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 71,
                    'sort' => 1,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            73 =>
                array (
                    'id' => 74,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'items-transitions-report',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ReportsController::class',
                    'action' => 'items_transitions_report',
                    'title' => 'كشف حركات الصنف',
                    'name' => 'admin.reports.items_transitions_report',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 71,
                    'sort' => 1,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            74 =>
                array (
                    'id' => 75,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'items-transitions-report/export-pdf',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ReportsController::class',
                    'action' => 'export_items_transitions_report',
                    'title' => 'تصدير التقرير',
                    'name' => 'admin.reports.export_items_transitions_report',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 71,
                    'sort' => 1,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            75 =>
                array (
                    'id' => 76,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'total-testament-report',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ReportsController::class',
                    'action' => 'total_testament_report',
                    'title' => 'كشف العُهد الإجمالي',
                    'name' => 'admin.reports.total_testament_report',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 71,
                    'sort' => 1,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            76 =>
                array (
                    'id' => 77,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'total-testament-report/export-pdf',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ReportsController::class',
                    'action' => 'export_total_testament_report',
                    'title' => 'تصدير التقرير',
                    'name' => 'admin.reports.export_total_testament_report',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 71,
                    'sort' => 1,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            77 =>
                array (
                    'id' => 78,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'detailed-testament-report',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ReportsController::class',
                    'action' => 'detailed_testament_report',
                    'title' => 'كشف العُهد المفصل',
                    'name' => 'admin.reports.detailed_testament_report',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 71,
                    'sort' => 1,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            78 =>
                array (
                    'id' => 79,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'detailed-testament-report/export-pdf',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ReportsController::class',
                    'action' => 'export_detailed_testament_report',
                    'title' => 'تصدير التقرير',
                    'name' => 'admin.reports.export_detailed_testament_report',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 71,
                    'sort' => 1,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            79 =>
                array (
                    'id' => 80,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'separate-item-balances-report',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ReportsController::class',
                    'action' => 'separate_item_balances_report',
                    'title' => 'كشف أرصدة الصنف المنفصل',
                    'name' => 'admin.reports.separate_item_balances_report',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 71,
                    'sort' => 1,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            80 =>
                array (
                    'id' => 81,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'separate-item-balances-report/export-pdf',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ReportsController::class',
                    'action' => 'export_separate_item_balances_report',
                    'title' => 'تصدير التقرير',
                    'name' => 'admin.reports.export_separate_item_balances_report',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 71,
                    'sort' => 1,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            81 =>
                array (
                    'id' => 82,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'detailed-employee-testament-transitions',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ReportsController::class',
                    'action' => 'detailed_employee_testament_transitions',
                    'title' => 'حركات عهدة الموظف التفصيلي',
                    'name' => 'admin.reports.detailed_employee_testament_transitions',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 71,
                    'sort' => 1,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            82 =>
                array (
                    'id' => 83,
                    'group_id' => 1,
                    'request_type' => 'get',
                    'url' => 'detailed-employee-testament-transitions/export-pdf',
                    'controller' => 'App\\Http\\Controllers\\Admin\\ReportsController::class',
                    'action' => 'export_detailed_employee_testament_transitions',
                    'title' => 'تصدير التقرير',
                    'name' => 'admin.reports.export_detailed_employee_testament_transitions',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'icon-briefcase',
                    'parent_id' => 71,
                    'sort' => 1,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
        ));


    }
}
